### PR TITLE
Use ts-node to run, rather than building each time

### PR DESCRIPTION
**Pull request by adambowles**

### CODE REVIEW

**Comment by adambowles** [comment]
Also added nodemon watching

**Comment by gruberb** [comment]
https://github.com/gruberb/YNABReporting/issues/8

**Comment by gruberb** [comment]
Hey @adambowles, thanks a lot for your help! Would you mind adding [tslint](https://github.com/palantir/tslint) and add a testing framework as well? So we could close the whole issue with one PR: https://github.com/gruberb/YNABReporting/issues/8

**Comment by adambowles** [comment]
Added tslint with standard starter config (https://standardjs.com)

**Comment by gruberb** [comment]
What do you think about testing frameworks? Should we implement one for `src/lib/getCommonWords.ts` as an example? 

We would need to run `tsc` first and run the tests within the `built` folder.

**Pull request merged**
